spring.application.name=expense-tracker

# ???? ?????????? DB_URL ?????? ????????, ?????????? ??. ???? ??? ? ?????????? localhost
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/expense_tracker_db}
spring.datasource.username=${DB_USER:expense_user}
spring.datasource.password=${DB_PASSWORD:nikita2003}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# ?????? ? ?????? ??? ?????? ?????? ????. ??? ????????? ?????????? ????????? 8080
server.port=${PORT:8080}